#pragma once

#ifndef __INTERGEN_GENERATED__data_ifc_JS_H__
#define __INTERGEN_GENERATED__data_ifc_JS_H__

//@file Javascript interface file for data_ifc interface generated by intergen
//See LICENSE file for copyright and license information

#include "data_ifc.h"

#include <comm/intergen/ifc.js.h>
#include <comm/token.h>

namespace js {

class data_ifc
{
public:
};

} //namespace js


#endif //__INTERGEN_GENERATED__data_ifc_JS_H__
